sonar.projectKey=tanhiowyatt_cyanide_honeypot
sonar.organization=tanhiowyatt

sonar.sources=src
sonar.tests=src/cyanide/tests
sonar.exclusions=src/cyanide/tests/**
sonar.python.coverage.reportPaths=coverage.xml

