[tox]
envlist = py311
skipsdist = True

[testenv]
deps = 
    .[dev]
    pytest-mock>=3.10.0
    pytest-cov>=4.1.0
setenv =
    PYTHONPATH = {toxinidir}/src
changedir = {toxinidir}
commands = pytest --cov=src tests/
