static:
  /bin/awk:
    content: ''
  /bin/bash:
    content: ''
  /bin/cat:
    content: ''
  /bin/cp:
    content: ''
  /bin/grep:
    content: ''
  /bin/gzip:
    content: ''
  /bin/ls:
    content: ''
  /bin/mkdir:
    content: ''
  /bin/mv:
    content: ''
  /bin/rm:
    content: ''
  /bin/sed:
    content: ''
  /bin/sh:
    content: ''
  /bin/tar:
    content: ''
  /etc/bashrc:
    content: ''
  /etc/centos-release:
    content: 'CentOS Linux release 7.9.2009 (Core)

      '
  /etc/fstab:
    content: '

      #

      # /etc/fstab

      # Created by anaconda on Thu Jan 25 16:17:31 2024

      #

      # Accessible filesystems, by reference, are maintained under ''/dev/disk''

      # See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info

      #

      /dev/mapper/centos-root /                       xfs     defaults        0 0

      UUID=a12b3c4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6 /boot                   xfs     defaults        0
      0

      /dev/mapper/centos-swap swap                    swap    defaults        0 0

      '
  /etc/group:
    content: 'root:x:0:

      bin:x:1:

      daemon:x:2:

      sys:x:3:

      adm:x:4:

      tty:x:5:

      disk:x:6:

      lp:x:7:

      mem:x:8:

      kmem:x:9:

      wheel:x:10:admin

      cdrom:x:11:

      mail:x:12:

      man:x:15:

      dialout:x:18:

      floppy:x:19:

      games:x:20:

      tape:x:33:

      video:x:39:

      ftp:x:50:

      lock:x:54:

      audio:x:63:

      nobody:x:99:

      users:x:100:

      utmp:x:22:

      utermbuf:x:199:

      input:x:999:

      systemd-journal:x:190:

      systemd-network:x:192:

      systemd-resolve:x:193:

      dbus:x:81:

      polkitd:x:998:

      ssh_keys:x:997:

      sshd:x:74:

      admin:x:1000:

      '
  /etc/hostname:
    content: '{{ hostname }}

      '
  /etc/hosts:
    content: '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4

      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

      127.0.1.1   {{ hostname }}

      '
  /etc/issue:
    content: '{{ os_name }}

      Kernel {{ kernel_version }} on an {{ arch }}


      '
  /etc/os-release:
    content: 'NAME="CentOS Linux"

      VERSION="{{ version_id }} (Core)"

      ID="{{ os_id }}"

      ID_LIKE="rhel fedora"

      VERSION_ID="{{ version_id }}"

      PRETTY_NAME="CentOS Linux {{ version_id }} (Core)"

      ANSI_COLOR="0;31"

      CPE_NAME="cpe:/o:centos:centos:{{ version_id }}"

      HOME_URL="https://www.centos.org/"

      BUG_REPORT_URL="https://bugs.centos.org/"

      '
  /etc/passwd.txt:
    content: 'root:x:0:0:root:/root:/bin/bash

      admin:x:1000:1000:admin:/home/admin:/bin/bash

      '
  /etc/profile:
    content: ''
  /etc/redhat-release:
    content: 'CentOS Linux release 7.9.2009 (Core)

      '
  /etc/resolv.conf:
    content: '# Generated by NetworkManager

      search localdomain

      nameserver 8.8.8.8

      nameserver 8.8.4.4

      '
  /etc/shadow:
    content: 'root:*:19450:0:99999:7:::

      bin:*:19450:0:99999:7:::

      daemon:*:19450:0:99999:7:::

      adm:*:19450:0:99999:7:::

      lp:*:19450:0:99999:7:::

      sync:*:19450:0:99999:7:::

      shutdown:*:19450:0:99999:7:::

      halt:*:19450:0:99999:7:::

      mail:*:19450:0:99999:7:::

      operator:*:19450:0:99999:7:::

      games:*:19450:0:99999:7:::

      ftp:*:19450:0:99999:7:::

      nobody:*:19450:0:99999:7:::

      systemd-network:!!:19450::::::

      systemd-resolve:!!:19450::::::

      dbus:!!:19450::::::

      polkitd:!!:19450::::::

      sshd:!!:19450::::::

      admin:$6$v.CkqC7f$6T5S9X...:19450:0:99999:7:::

      '
  /etc/shells:
    content: '/bin/sh

      /bin/bash

      /usr/bin/sh

      /usr/bin/bash

      '
  /etc/ssh/sshd_config:
    content: "# host key for protocol version 1\n#HostKey /etc/ssh/ssh_host_key\n\
      # host keys for protocol version 2\nHostKey /etc/ssh/ssh_host_rsa_key\n#HostKey\
      \ /etc/ssh/ssh_host_dsa_key\nHostKey /etc/ssh/ssh_host_ecdsa_key\nHostKey /etc/ssh/ssh_host_ed25519_key\n\
      \n# Syslog\nSyslogFacility AUTHPRIV\n#LogLevel INFO\n\n# Authentication:\n#LoginGraceTime\
      \ 2m\nPermitRootLogin yes\n#StrictModes yes\n#MaxAuthTries 6\n#MaxSessions 10\n\
      \nPubkeyAuthentication yes\n\n# The default is to check both .ssh/authorized_keys\
      \ and .ssh/authorized_keys2\n# but this is overridden so installations will\
      \ only check .ssh/authorized_keys\nAuthorizedKeysFile\t.ssh/authorized_keys\n\
      \n# For this to work you will also need host keys in /etc/ssh/ssh_known_hosts\n\
      #HostbasedAuthentication no\n# Change to yes if you don't trust ~/.ssh/known_hosts\
      \ for\n# HostbasedAuthentication\n#IgnoreUserKnownHosts no\n# Don't read the\
      \ user's ~/.rhosts and ~/.shosts files\n#IgnoreRhosts yes\n\n# To disable tunneled\
      \ clear text passwords, change to no here!\n#PasswordAuthentication yes\n#PermitEmptyPasswords\
      \ no\nPasswordAuthentication yes\n\n# GSSAPI options\nGSSAPIAuthentication yes\n\
      GSSAPICleanupCredentials yes\n\n# Use PAM\nUsePAM yes\n\n# Standard SSH settings\n\
      Subsystem\tsftp\t/usr/libexec/openssh/sftp-server\nX11Forwarding yes\nPrintMotd\
      \ no\n"
  /home/admin/.bashrc:
    content: "# .bashrc\n\n# Source global definitions\nif [ -f /etc/bashrc ]; then\n\
      \t. /etc/bashrc\nfi\n\n# Uncomment the following line if you don't like systemctl's\
      \ auto-paging feature:\n# export SYSTEMD_PAGER=\n\n# User specific aliases and\
      \ functions\nalias ls='ls --color=auto'\nalias ll='ls -l'\n"
  /root/.bashrc:
    content: "# .bashrc\n\n# User specific aliases and functions\nalias rm='rm -i'\n\
      alias cp='cp -i'\nalias mv='mv -i'\n\n# Source global definitions\nif [ -f /etc/bashrc\
      \ ]; then\n\t. /etc/bashrc\nfi\n"
  /usr/bin/python3:
    content: ''
  /usr/bin/systemctl:
    content: ''
  /usr/bin/vim:
    content: ''
  /usr/bin/yum:
    content: ''
