metadata:
  os_name: "Debian 11 (Bullseye)"
  kernel_version: "5.10.0-28-amd64"
  hostname: "debian-server"
  arch: "x86_64"
  ssh_banner: "SSH-2.0-OpenSSH_8.4p1 Debian-5+deb11u1"
  os_id: "debian"
  version_id: "11"
  install_date: "2024-01-31T10:00:00Z"

honeytokens:
  - "/etc/passwd"
  - "/etc/shadow"

dynamic_files:
  /proc/uptime:
    type: generated
    provider: uptime_provider
  /proc/cpuinfo:
    type: generated
    provider: cpuinfo_provider
  /proc/version:
    content: "Linux version {{ kernel_version }} (debian-kernel@lists.debian.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.209-2 (2024-01-31)"
  /etc/motd:
    type: generated
    provider: motd_provider
